name: Fuzz parser

# Run this workflow on changes to the external scanner
on:
  push:
  pull_request:

jobs:
  test:
    name: Parser fuzzing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vigoux/tree-sitter-fuzz-action@v1
        with:
          language: purescript
          external-scanner: src/scanner.c
          time: 60
          timeout: 5
